//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public System.DateTime RegisterTime { get; set; }
        public string DataMatrix { get; set; }
        public string RawID { get; set; }
        public string Action { get; set; }
        public Nullable<System.DateTime> RemainingTime { get; set; }
        public string UserName { get; set; }
        public string Comment { get; set; }
    }
}
