//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSL_Entities : DbContext
    {
        public MSL_Entities(string connStr)
            : base(connStr)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<Definition> Definitions { get; set; }
        public virtual DbSet<InstancesConfiguration> InstancesConfigurations { get; set; }
        public virtual DbSet<Reel> Reels { get; set; }
        public virtual DbSet<ReelsAction> ReelsActions { get; set; }
        public virtual DbSet<UserCommand> UserCommands { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<View_Reels_Levels> View_Reels_Levels { get; set; }
    }
}
