//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reel
    {
        public int ReelId { get; set; }
        public string RAWID { get; set; }
        public System.DateTime ExpireDateTime { get; set; }
        public int ResetCounter { get; set; }
        public System.DateTime ResetCounterDateTime { get; set; }
        public int UserId { get; set; }
        public int MSLId { get; set; }
        public System.DateTime Created { get; set; }
    }
}
