//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReelsAction
    {
        public int Id { get; set; }
        public System.DateTime DateTimeRegistered { get; set; }
        public string Identificator { get; set; }
        public string Action { get; set; }
        public System.DateTime RemainingTime { get; set; }
        public string Location { get; set; }
    }
}
